# Generated by Django 4.2.28 on 2026-03-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Operator', 'operator'), ('Admin', 'admin'), ('User', 'user')], default='User', max_length=10),
        ),
    ]
