# Generated by Django 4.2.28 on 2026-03-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_users_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="points",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
