# Generated by Django 4.2.28 on 2026-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="gmail",
            field=models.EmailField(
                blank=True, default="none@gmail.com", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
