# Generated by Django 4.2.28 on 2026-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="image",
            new_name="avatar",
        ),
        migrations.AddField(
            model_name="users",
            name="gmail",
            field=models.EmailField(
                blank=True, default="none@gmail.com", max_length=254, null=True
            ),
        ),
    ]
