# Generated by Django 4.2.28 on 2026-03-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('Go', 'go'), ('Pro', 'pro'), ('Ultima', 'ultima')], max_length=10)),
                ('duration_type', models.CharField(choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('version', 'duration_type')},
            },
        ),
        migrations.CreateModel(
            name='ExtendedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.extraplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
